cyclus/cyclus.github.com

- source/cite/index.rst
- source/cite/meetings/2014.10.23.ANL.rst
Finally got time to make my Cyclus build work and publish the last PR.  This one adds the Vegas presentations and a demo link for the ANL meeting using substitutions to preserve the table formatting.
> Add figshare link

- source/arche/testing.rst
- source/arche/toolkit.rst
Docs for cyclus/cyclus#1076.  This still has a link that doesn't have a url because it links to api docs that aren't merged/published yet.  So I'll need to update this after 1076 goes in.
> docs for MockSim

- source/cyclusagent.py
* Use subheadings for State variables, and schema sections rather than just
bold text on its own line.
* Move misc annotations into their own "Other Info" subheading section rather
than just below the doc paragraph.  This section is placed below everything
except the schema
* Move state variable units annotation onto the same line as state var header
right next to the variable type - e.g. :[statevarname]: ``double`` kg.
* Don't print the tooltip if there is a doc annotation.  tooltip is a fallback
only if necessary.  This eliminates redundant/annoying info and makes the docs
much nicer to look at.
> Make archetype docs even prettier

- source/cyclusagent.py
You now get better looking "other info" listings
> updating 'other info' for cleaner key names

- source/atemplates/layout.html
Just realized that the link for the dev list pointed to the user list.
> Fix link for dev list

- Makefile
- README.rst
* Add more instructions to readme for updating website deps image
* Modify/add "serve" make targets to support python3 in addition to allowing
servince pre-built files (e.g. to enable serving a docker build)
> Add details for improving docker usage experience:

- source/arche/index.rst
- source/atemplates/layout.html
- source/index.rst
- source/user/index.rst
- source/user/install.rst
- source/user/install_binary.rst
- source/user/install_tarball.rst
Started changes outlined in Issue #198. I have worked on #1,#2 from that list, with outstanding tasks listed below. #3 has not been addressed with this PR.
To Do:
user/tutorial/install_launch_cyclist.rst - update installers (Linux, Mac, Windows)
user/install_binary.rst - update instructions to include install from Debian binary. Possibly split out basic Conda install instructions into a new file
user/virtualbox.rst - update cyclus ova file
user/install_tarball.rst - build this page with instructions, build tarball to link to (Linux & Mac)
kernel/install_from_source - revamp this page with Baptiste's detailed installation instructions from the README (Linux & Mac)
> Clean install docs

- source/atemplates/layout.html
- source/index.rst
- source/previous/v1.4.rst
only missing things to complete the website 1.4 release are the DOI of Cyclus/Cycamore/Cymetric 1.4. 
Figshare package are almost ready
> update some information about 1.4

- source/user/install_binary.rst
removing u14 mentions
can be tested using my u14_deprecation branch for cyclus and cycamore:
`make gh-preview GIT_BRANCH=u14_deprecation_ GIT_FORK=baaaaam`
> u14 deprecation

- source/cep/cep3.rst
- source/user/dbdoc.rst
> WIP: update CEP3 to actual release process.

- source/arche/index.rst
Google left googlecode behind a while back and now hosts everything on github, so our link on the style guide section is now dead. This fixes the link.
> updates style guide link.

- source/cep/cep-0003-1.svg
- source/cep/cep3.rst
Hello All, This modification to CEP3 proposes that we drop the [GitFlow workflow](https://datasift.github.io/gitflow/IntroducingGitFlow.html) in favor of the master-is-develop workflow.  Many minor modifications had to made throughout the CEP, so the changes are spread out with no single section receiving a major rewrite.
At the community meeting in July, there was support for this.  This will also pave the way for external projects (that is rickshaw) to be brought into the Cyclus organization.
> Release Management Changes to CEP3

- source/user/install.rst
cyclist is not supported anymore...
removing any mention in the installation instruction
> removing cyclist mentions in the installation instruction

- source/cep/cep3.rst
This file includes a version number that should be updated when bumping version numbers for new releases. I've added the file to the instructions.
> CEP3: Updating Cyclus Release Procedure Instructions

- Makefile
Added this, to ensure `make xxx-publish` is using an up-to-date version of `master` and `source` to build and publish the last version of the website.
Context:
Earlier today, I try to publish the new version of the website, the process requires you to have a local `master` branch, which I did not have... So I created it from `source` not from `upstream/master`.
I then ran the build and publish process (which updates and push a new version of `master`) but as my `master` was a copy of `source` and not `master` it did not include the pre-built files required for the website... and so it broke the website...
This should ensure that nobody make this kind of mistake in the future:
the `git check -B master upstream/master` creates a new `master` branch locally if it did not already exist, or …
> force updating/creating local/master from upstream/master on publish

- source/cep/cep27.rst
This is a suggestion to improve, ease and homogenize an the usage of toolkit capability in archetypes.
This idea is to limit as much as possible the need for implementation in a newly develop archetypes to avoid divergence in the implementation and the convention by providing a snippet that one can simply includes in the archetypes class definition header (inside the core definition of the class) to ensure variable name are identical.
Example can be found in:
- cyclus/cyclus#1510 for the snippet implementation
- cyclus/cycamore#502 for the corresponding archetypes implementations
> CEP27: toolkit Snippet

- source/user/tutorial/add_arche.rst
- source/user/tutorial/add_commod_recipe.rst
- source/user/tutorial/add_proto.rst
Fixes #311 
The footnote that clarifies that order doesn't matter is repeated more often.
> proliferate foot notes about order

- README.rst
- source/arche/dre.rst
- source/arche/dynamic_loading.rst
- source/arche/hello_world_py.rst
- source/arche/tutorial_py/index.rst
- source/arche/tutorial_py/setup.rst
- source/arche/tutorial_py/state_var.rst
- source/arche/tutorial_py/toolkit.rst
- source/conf.py
- source/cyclusagent.py
- source/numpydoc/numpydoc.py
- source/user/install.rst
This PR reflects changes made in [Cyclus PR #1594](https://github.com/cyclus/cyclus/pull/1594) to add some functionality to the Python API for creating material requests. There are also some small typo fixes on a few other pages around the site. 
This should *not* be merged until after Cyclus PR #1594 is merged.
> Update Python API for archetype development

- source/atemplates/layout.html
The sidebar menu in the layout template only refers to a single archetype developer tutorial, with the wrong URL.
Fixes cyclus/cyclus#1565
> expose both archetype tutorials on sidebar menu

- source/user/index.rst
This PR adds links to the Cyclus user guide for the following third-party archetypes (TPA)s:
* Peddler
* Cyder
* OpenMCyclus
* D3ploy
* ann_pwr
It also removes descriptions of individual archetypes from the previously listed TPAs.
This PR closes #327
> Third-party archetype list update

- Makefile
This should correctly avoid the inclusion of the `source` directory in the published website branch `main`.
A related PR #346 has been issued to `main` to include both these changes to the `Makefile` and to delete the `source` directory.
Ideally, review/merge #346 before this PR
> fix treatment of source in website build

- Makefile
- README.rst
- gh-project.mk
- rever.xsh
- source/kernel/build_from_source.rst
- source/kernel/contributing_to_cyclus.rst
- source/kernel/style_guide.rst
- source/numpydoc/numpydoc.py
- source/user/tutorial/run_cyclus_native.rst
This PR changes the instances of `master` branch to `main` branch, now that we have changed the default branch for Cyclus, Cycamore, and Cymetric. This addresses one of the item in #337
> change instances of master branch to main
