cyclus/cyclus.github.com

source/kernel/contributing_to_cyclus.rst, source/kernel/index.rst, source/kernel/pr_review.rst
Here's a summary of recommendations for reviewing pull requests, as per today's discussion. Feel free to improve upon it or let me know if I have mis-recorded anything.
=> Code review

source/cep/cep-0002-1.bib, source/cep/cep2.rst
A concrete proposal w.r.t. https://groups.google.com/forum/#!topic/cyclus-dev/ml5zMNVc05Y
=> suggestions for cep2 refinement

source/arche/cycpp.rst
Same a #137 but to the release branch.
=> [release branch] added greater alias documentation

source/arche/cycpp.rst
fixes #135 and supports cyclus/cyclus#1143
=> added greater alias documentation

source/cyclusagent.py
Sample xml input snippets are generated for each state variable.  The header
for optional state variables now explicitly says:
optional (default=[defualt])
Here is a screenshot:
=> [release branch] better auto-generated agent docs

source/cyclusagent.py
=> include useful uitype and units info in sample xml snippets

source/cite/tutorials/2015-ans-archdev.rst, source/cite/tutorials/2015-ans-users.rst, source/index.rst
Here are some landing pages for the tutorials with more information promised by June 1.
=> Add basic info about upcoming tutorials

source/cep/cep0.rst, source/cep/cep6.rst
A suggested style guide for code base pull requests
=> added text for PR style cep

source/index.rst
I added mention of the M&C Roundtable and the FCWM technical session.
=> Expand description of 2015 ANS Annual events

source/cep/cep0.rst, source/cep/cep24.rst
hi folks, another cep for you all related to preference adjustment
=> adding proposal for cep24

source/index.rst, source/news/fy16neup.rst
Added news section to capture specific items - will require curation.
=> News section on front page

source/user/input_specs/archetypes.rst, source/user/input_specs/commodity.rst, source/user/input_specs/control.rst, source/user/input_specs/facility.rst, source/user/input_specs/inst.rst, source/user/input_specs/recipe.rst, source/user/input_specs/region.rst
=> Commodity json

source/cyclusagent.py, source/user/find_agents.rst, source/user/input_specs/control.rst, source/user/input_specs/facility.rst, source/user/input_specs/inst.rst, source/user/input_specs/recipe.rst, source/user/input_specs/region.rst, source/user/writing_input.rst
Updated writing_input file with JSON code added.
=> writing_input2

source/cyclusagent.py
=> updated cyclusagents.py file with json code generation

source/cyclusagent.py
The website build was broken by some additions for json snippet generation/printing in #186.  This should fix those issues.
=> fix tab and incorrect python3 string handling

source/user/cymetric/tutorial.rst
- added some needed details (testing and dependencies)
- attached links to words instead
- small edits/formatting
@mbmcgarry, I'm wondering if you could review this since you brought a few things to light that were missing or confusing to you. I am sure I didn't capture all of it!
=> small edits to cymetric tutorial

source/cep/cep3.rst
Helps address cyclus/cyclus#1181.
=> note about running smbchk tool on a release build

source/extern/CYCLUS_INSTALL.rst, source/user/install.rst, source/user/install_binary.rst, source/user/install_cycamore_from_source.rst, source/user/install_cyclus_from_source.rst, source/user/install_from_git.rst, source/user/install_from_tarball.rst, source/user/unit_test.rst, source/user/virtualbox.rst
The installation instructions overhaul looks great @Baaaaam !!
=> general editing and formatting

source/user/install.rst, source/user/tutorial/install_launch_cyclist.rst
move cyclist tutorial at the end of cyclist install
=> move cyclist tutorial 

AUTHORS.rst, LICENSE.rst, Makefile, source/conf.py, source/index.rst, source/user/install.rst, source/user/install_binary.rst, source/user/install_from_git.rst, source/user/install_from_tarball.rst
This depends on cyclus PR https://github.com/cyclus/cyclus/pull/1301 and cycamore PR https://github.com/cyclus/cycamore/pull/433
=> Pphw dox rev2

source/arche/cycpp.rst, source/arche/testing.rst, source/previous/index.rst, source/previous/v1.4.rst, source/user/cycamoreagents.rst, source/user/dbdoc.rst, source/user/input_specs/control.rst
push @rwcarlsen branch into the install_docs_reworks branch 
it still need to be updated with the last change (between RC3 and actual release)
=> Rwcarlsen upd release

source/cite/citecyc.bib, source/index.rst, source/previous/index.rst
update last information for the release:
- DOI for Cyclus/Cycamore/Cymetric
- front page
- layout
- bib citation
- author list
=> Release date up

source/user/install_binary.rst
update installation instruction for cycamore deb package
this need to be published after the merge of the cyclus/cycamore#445
=> Up install 1.5

source/index.rst
adding  previous FC workshop.
shall we add the link to the different Cyclus presentation as well ?
=> adding TWDNFC

source/cep/cep3.rst
- small syntax fix
- update modification date
- add BaM as an author (not sure what is the policy there, if the listed author are the orignal author only, or any one who updated it)
=> few fix on CEP3

Makefile, source/cyclusagent.py, source/python/agents.rst
CC @bam241 @FlanFlanagan @hodger
=> various fixes for documentation building

source/user/install_from_tarball.rst
Updated install_from_tarball.rst file to resolve issue https://github.com/cyclus/cyclus/issues/1369
=> changes to resolve cyclus core version related issue

source/arche/toolkit.rst
Added GIS documentation for PR#1390 in cyclus/cyclus
=> GIS Documentation in toolkit

source/cep/cep1.rst
This was discussed and approved back at the Community meeting in July, but please feel free to comment
=> CEP1 modification: lazy consensus for languishing CEPs

source/cep/cep-0002-1.svg, source/cep/cep-0002-2.svg, source/cep/cep2.rst
This is a modification to CEP2 that allows for something like Rickshaw
=> Simulation Orchestration Concern 

source/newsletters/oct2017.rst, source/newsletters/pubs.bib
adding links, 
and some publications..
@FlanFlanagan shall we not shape the publications as references ? (it will take less place...)
=> some newsletter update

source/arche/timestep.rst, source/arche/tutorial_cpp/index.rst, source/astatic/cyclus.css_t, source/index.rst, source/user/install_binary.rst
Some minor fixes to remove some of the issues on github/clean up some info.
=> Minor fixes

source/index.rst, source/newsletters/oct2017.rst, source/newsletters/pubs.bib
@skc222 @katyhuff @gonuke @bam241 @scopatz 
First draft of the newsletter. I'll be making edits in the near future to add somethings in. But I figured I'd let those that have things they would like to add be able to add them.
=> first draft of the news letter

source/cep/cep3.rst, source/kernel/build_from_source.rst, source/kernel/build_with_conda.rst, source/user/install.rst
A few lines that will make development easier going forward.
=> micro version number modification to cep3

source/astatic/cyclus.css_t, source/index.rst
This should fix the issue you were having @gonuke. It also fixes the dev call line. 
I does not fix the text issue on the sidebar however. Word wrapping needs to be added in some capacity but I'm having trouble forcing that in that section of the html.
=> Fixing sidebar

source/atemplates/layout.html, source/index.rst
Just starting this. I will be adding the notes and attempting to add it to the top bar of the website soon.
=> fixed time and added hangout link

source/atemplates/layout.html
The PR we just merged had a bug.
=> Fix poorly formatted URL

Makefile
this propagates the changes in Makefile from `source` branch
=> importing new Makefile from source

source/user/tutorial/launch_cyclus.rst, source/user/tutorial/run_cyclus_native.rst, source/user/tutorial/sim_parm.rst
I fixed a few of the broken links in the tutorial that were identified in issues #313, #312, and #309.
=> Fixes some of the broken links

source/user/tutorial/add_commod_recipe.rst, source/user/tutorial/add_proto.rst
I forgot about this when I approved and merged PR #318. I added in a header for each of the footnotes added in with PR #318.
=> added heading for footnotes

source/index.rst
Removing Cloudlus web-base interface and adding a out-of-service message
=> Retiring Cloudlus

source/cep/cep0.rst
CEP27 was approved in #297, but never added to the list of CEPs.
=> Add CEP27 to list

source/conf.py
Automatically update the copyright year to the current year - tested with the docker preview
=> Auto copy year
